### ISSUE TITLE
fix apidoc

### ISSUE THREAD

**Issue by Willtock** [EBM-2017-2018/OKLM#15]
Problème de route dans l'apidoc pour la suppression de catégorie

Route actuelle : /api/documents/:id 

Elle devrait être : /api/categories/:id

**Comment by Ekarz** [comment]
en cours de PR

**Comment by nymous** [comment]
Faut pas fermer l'issue comme ça, faut link vers la PR ici ^^
(Le mieux étant de faire un commit avec comme message "Fix #15", et GitHub fermera l'issue tout seul)
